"""initial_schema

Revision ID: b2b2972d979f
Revises: 
Create Date: 2026-03-23 02:09:31.427893

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2b2972d979f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('products',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_org_id'), 'products', ['org_id'], unique=False)
    op.create_index(op.f('ix_products_owner_id'), 'products', ['owner_id'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=False)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_deleted_at'), 'suppliers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_org_id'), 'suppliers', ['org_id'], unique=False)
    op.create_index(op.f('ix_suppliers_owner_id'), 'suppliers', ['owner_id'], unique=False)
    op.create_index(op.f('ix_suppliers_slug'), 'suppliers', ['slug'], unique=False)
    op.create_table('uploaded_files',
    sa.Column('original_name', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_type', sa.Enum('PDF', 'IMAGE', 'INVOICE', 'SUPPLIER_FILE', 'OTHER', name='uploaded_file_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PROCESSED', 'FAILED', name='uploaded_file_status_enum'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uploaded_files_deleted_at'), 'uploaded_files', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_uploaded_files_id'), 'uploaded_files', ['id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_org_id'), 'uploaded_files', ['org_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_owner_id'), 'uploaded_files', ['owner_id'], unique=False)
    op.create_index(op.f('ix_uploaded_files_status'), 'uploaded_files', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('uploaded_file_id', sa.UUID(), nullable=False),
    sa.Column('doc_type', sa.Enum('INVOICE', 'SUPPLIER_CATALOG', 'PRICE_LIST', 'OTHER', name='document_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'EXTRACTING', 'COMPLETED', 'FAILED', name='document_status_enum'), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_file_id'], ['uploaded_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_org_id'), 'documents', ['org_id'], unique=False)
    op.create_index(op.f('ix_documents_owner_id'), 'documents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_file_id'), 'documents', ['uploaded_file_id'], unique=False)
    op.create_table('price_estimations',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('estimated_price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_type', sa.Enum('HISTORICAL_INVOICE', 'SUPPLIER_CATALOG', 'WEB_SCRAPE', 'AI_ESTIMATED', 'MANUAL', name='price_source_type_enum'), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_estimations_id'), 'price_estimations', ['id'], unique=False)
    op.create_index(op.f('ix_price_estimations_org_id'), 'price_estimations', ['org_id'], unique=False)
    op.create_index(op.f('ix_price_estimations_owner_id'), 'price_estimations', ['owner_id'], unique=False)
    op.create_index(op.f('ix_price_estimations_product_id'), 'price_estimations', ['product_id'], unique=False)
    op.create_index(op.f('ix_price_estimations_source_type'), 'price_estimations', ['source_type'], unique=False)
    op.create_table('product_aliases',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('alias_text', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_aliases_alias_text'), 'product_aliases', ['alias_text'], unique=False)
    op.create_index(op.f('ix_product_aliases_id'), 'product_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_product_aliases_org_id'), 'product_aliases', ['org_id'], unique=False)
    op.create_index(op.f('ix_product_aliases_owner_id'), 'product_aliases', ['owner_id'], unique=False)
    op.create_index(op.f('ix_product_aliases_product_id'), 'product_aliases', ['product_id'], unique=False)
    op.create_table('supplier_products',
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_products_id'), 'supplier_products', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_products_org_id'), 'supplier_products', ['org_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_owner_id'), 'supplier_products', ['owner_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('ai_jobs',
    sa.Column('job_type', sa.Enum('OCR', 'PDF_PARSE', 'IMAGE_PARSE', 'PRODUCT_EXTRACTION', 'PRICE_ESTIMATION', 'EMBEDDING', 'WEB_SCRAPE', name='ai_job_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='ai_job_status_enum'), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_jobs_document_id'), 'ai_jobs', ['document_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_id'), 'ai_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_job_type'), 'ai_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_ai_jobs_org_id'), 'ai_jobs', ['org_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_owner_id'), 'ai_jobs', ['owner_id'], unique=False)
    op.create_index(op.f('ix_ai_jobs_status'), 'ai_jobs', ['status'], unique=False)
    op.create_table('extracted_items',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('matched_product_id', sa.UUID(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_items_document_id'), 'extracted_items', ['document_id'], unique=False)
    op.create_index(op.f('ix_extracted_items_id'), 'extracted_items', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_items_matched_product_id'), 'extracted_items', ['matched_product_id'], unique=False)
    op.create_index(op.f('ix_extracted_items_org_id'), 'extracted_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_extracted_items_owner_id'), 'extracted_items', ['owner_id'], unique=False)
    op.create_table('invoices',
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('invoice_number', sa.String(length=128), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_deleted_at'), 'invoices', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_invoices_document_id'), 'invoices', ['document_id'], unique=False)
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_invoices_org_id'), 'invoices', ['org_id'], unique=False)
    op.create_index(op.f('ix_invoices_owner_id'), 'invoices', ['owner_id'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.create_table('invoice_items',
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('raw_description', sa.Text(), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_items_id'), 'invoice_items', ['id'], unique=False)
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_product_id'), 'invoice_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_items_product_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_id'), table_name='invoice_items')
    op.drop_table('invoice_items')
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_owner_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_org_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_document_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_deleted_at'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_extracted_items_owner_id'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_org_id'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_matched_product_id'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_id'), table_name='extracted_items')
    op.drop_index(op.f('ix_extracted_items_document_id'), table_name='extracted_items')
    op.drop_table('extracted_items')
    op.drop_index(op.f('ix_ai_jobs_status'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_owner_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_org_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_job_type'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_id'), table_name='ai_jobs')
    op.drop_index(op.f('ix_ai_jobs_document_id'), table_name='ai_jobs')
    op.drop_table('ai_jobs')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_owner_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_org_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_product_aliases_product_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_owner_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_org_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_id'), table_name='product_aliases')
    op.drop_index(op.f('ix_product_aliases_alias_text'), table_name='product_aliases')
    op.drop_table('product_aliases')
    op.drop_index(op.f('ix_price_estimations_source_type'), table_name='price_estimations')
    op.drop_index(op.f('ix_price_estimations_product_id'), table_name='price_estimations')
    op.drop_index(op.f('ix_price_estimations_owner_id'), table_name='price_estimations')
    op.drop_index(op.f('ix_price_estimations_org_id'), table_name='price_estimations')
    op.drop_index(op.f('ix_price_estimations_id'), table_name='price_estimations')
    op.drop_table('price_estimations')
    op.drop_index(op.f('ix_documents_uploaded_file_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_owner_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_org_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_uploaded_files_status'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_owner_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_org_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_id'), table_name='uploaded_files')
    op.drop_index(op.f('ix_uploaded_files_deleted_at'), table_name='uploaded_files')
    op.drop_table('uploaded_files')
    op.drop_index(op.f('ix_suppliers_slug'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_owner_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_org_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_deleted_at'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_owner_id'), table_name='products')
    op.drop_index(op.f('ix_products_org_id'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
